#:schema https://raw.githubusercontent.com/YunoHost/apps/master/schemas/manifest.v2.schema.json

packaging_format = 2

id = "timebank-cc"
name = "Timebank_cc"
description.en = "Your time is currency"
description.fr = "Your time is currency" #TODO: translate to French

version = "0.0.01~ynh1"

maintainers = ["ronaldhuynen"]

[upstream]
license = "AGPL-3.0-only"
website = "https://timebank.cc/"
demo = ""
admindoc = "TODO: link to install guide on Github"
code = "TODO: link to Github repo"

[integration]
yunohost = ">= 11.2"
architectures = "all"
multi_instance = true

ldap = false

sso = false

disk = "50M"
ram.build = "100M"
ram.runtime = "100M"

[install]
    [install.domain]
    type = "domain"

    [install.init_main_permission]
    type = "group"
    default = "visitors"

    [install.admin]
    type = "user"

    [install.password]
    type = "password"

    [install.phpversion]
    ask.en = "Choose a PHP version you want to use for your app"
    ask.fr = "Choisissez une version PHP que vous souhaitez utiliser pour votre application"
    type = "select"
    choices = ["8.1"]
    default = "8.1"
    

[resources]

    [resources.sources]

        [resources.sources.main]
        # Mind the tar.gz extension:
        # Copy the zip file link and rename to tar.gz and download again. 
        # Calculate the sha256 locally: sha256sum /path/to/your/file.tar.gz.
        # After each commit this resource changes incl the checksum, so this should be a release file
        # not a commit file.
        url = "https://github.com/ronaldhuynen/timebank_cc_2/archive/refs/heads/Messenger.tar.gz"
        sha256 = "fa4b4320ca70fa7464a566c1413c497723e8142b98954bba554f6d365c054732"
        autoupdate.strategy = "latest_github_tag"

    [resources.system_user]

    [resources.install_dir]

    [resources.permissions]
    main.url = "/"

    [resources.apt]
    #TODO: Update packages for Timebank_CC
    packages = "mariadb-server, php8.1-mysql, php8.1-mbstring, php8.1-xml, php8.1-imap, php8.1-zip, php8.1-gd, php8.1-curl, php8.1-intl"

    [resources.database]
    type = "mysql"

    [resources.ports]
    # Websockets broadcasting service uses port 6001 
    main.default = 6001
