#:schema https://raw.githubusercontent.com/YunoHost/apps/master/schemas/manifest.v2.schema.json

packaging_format = 2

id = "timebank-cc"
name = "Timebank_cc"
description.en = "Your time is currency"
description.fr = "Your time is currency" #TODO: translate to French

version = "0.0.01~ynh1"

maintainers = ["ronaldhuynen"]

[upstream]
license = "AGPL-3.0-only"
website = "https://timebank.cc/"
demo = ""
admindoc = "TODO: link to install guide on Github"
code = "TODO: link to Github repo"

[integration]
yunohost = ">= 11.2"
architectures = "all"
multi_instance = false

ldap = false

sso = false

disk = "50M"
ram.build = "100M"
ram.runtime = "100M"

[install]
    [install.domain]
    type = "domain"

    [install.init_main_permission]
    type = "group"
    default = "visitors"

    [install.admin]
    type = "user"

    [install.password]
    type = "password"

[resources]

    [resources.sources]

        [resources.sources.main]
        #TODO! Change to timebank_cc repo release. Mind the tar.gz extension:
        # Copy the zip file link and rename to tar.gz and download again. 
        # Calculate the sha256 locally: sha256sum /path/to/your/file.tar.gz.
        # After each commit this resource changes incl the checksum, so this should be a release file
        # not a commit file.
        url = "https://github.com/ronaldhuynen/timebank_cc_2/archive/refs/heads/master.tar.gz"
        sha256 = "d092235aa2e8c67d681d887a6c5202acd9788d0d37321d8d2046b8c56409dd70"
        autoupdate.strategy = "latest_github_tag"

    [resources.system_user]

    [resources.install_dir]

    [resources.permissions]
    main.url = "/"

    [resources.apt]
    #TODO: Update packages for Timebank_CC
    packages = "mariadb-server, php8.2-mysql, php8.2-mbstring, php8.2-xml, php8.2-imap, php8.2-zip, php8.2-gd, php8.2-curl, php8.2-intl"

    [resources.database]
    type = "mysql"
