#!/bin/bash

#=================================================
# GENERIC START
#=================================================
# IMPORT GENERIC HELPERS
#=================================================

source _common.sh
source /usr/share/yunohost/helpers

email=$(ynh_user_get_info --username=$admin --key=mail)
firstname=$(yunohost user list --fields firstname --output-as json | jq  -r .users.$admin.firstname)
lastname=$(yunohost user list --fields lastname --output-as json | jq  -r .users.$admin.lastname)
timezone=$(cat /etc/timezone)

#=================================================
# APP "BUILD" (DEPLOYING SOURCES, VENV, COMPILING ETC)
#=================================================
# DOWNLOAD, CHECK AND UNPACK SOURCE
#=================================================
ynh_script_progression --message="Setting up source files..." --weight=1

ynh_setup_source --dest_dir="$install_dir"

chmod -R o-rwx "$install_dir"
chown -R $app:www-data "$install_dir"

usermod -g www-data $app
find $install_dir -type f -exec chmod 664 {} \;    
find $install_dir -type d -exec chmod 775 {} \;

#=================================================
# SYSTEM CONFIGURATION
#=================================================

ynh_script_progression --message="Adding system configurations related to $app..." --weight=1

ynh_add_fpm_config

ynh_add_nginx_config

ynh_add_config --template="cron" --destination="/etc/cron.d/$app"
chown root: "/etc/cron.d/$app"
chmod 644 "/etc/cron.d/$app"

env_path="$install_dir"
ynh_add_systemd_config
sudo chmod 644 /etc/systemd/system/$app.service

#=================================================
# APP INITIAL CONFIGURATION
#=================================================
# ADD A CONFIGURATION
#=================================================
ynh_script_progression --message="Adding a configuration file..." --weight=1

ynh_add_config --template=".env.example" --destination="$install_dir/.env"

chmod 600 "$install_dir/.env"
chown $app:$app "$install_dir/.env"

#=================================================
# INSTALL DEPENDENCIES
#=================================================
ynh_script_progression --message="Installing dependencies..." --weight=1

ynh_install_app_dependencies $pkg_dependencies

# Install composer
ynh_install_composer
#ynh_composer_exec --workdir="$install_dir" --commands="install"
#ynh_composer_exec --commands="install --prefer-dist --no-cache --no-progress --no-dev -a"
ynh_composer_exec --workdir="$install_dir" --commands="install --prefer-dist --no-cache --no-progress -a"

# Install npm
ynh_install_nodejs --nodejs_version=$YNH_NODEJS_VERSION
pushd "$install_dir"
	ynh_use_nodejs
	npm install
	npm install jquery --save
popd




#=================================================
# FINAL INSTALL
#=================================================
ynh_script_progression --message="Install $app" --weight=5

pushd $install_dir
	php$phpversion artisan key:generate --no-interaction --force
	php$phpversion artisan config:clear
	php$phpversion artisan storage:link
	php$phpversion artisan migrate --no-interaction --force
	# Do not create admin user, as the app will create one during the first db migration
	#php$phpversion artisan freescout:create-user --role=admin --firstName=$firstname --lastName=$lastname --email=$email --password=$password --no-interaction
	
	chgrp -R www-data storage bootstrap/cache public/css public/js
	chmod -R ug+rwx storage bootstrap/cache public/css public/js
	chmod +x artisan
	sudo npm run dev	#TODO: change to production when ready!
popd


#=================================================
# START SERVICES
#=================================================
ynh_script_progression --message="Starting systemd services..." --weight=2

# Start the systemd service
ynh_systemd_action --service_name=$app --action=start --log_path="/var/log/$app/$app.systemd.log"

# Add and start the websocket service
yunohost service add "$app-websockets" --description="$app websockets service"
ynh_systemd_action --service_name=${app}-web --action=start --log_path="/var/log/$app/$app.websockets.log"

#=================================================
# RELOAD NGINX
#=================================================

systemctl reload nginx

#=================================================
# END OF SCRIPT
#=================================================
ynh_script_progression --message="Installation of $app completed" --last
